# Generated by Django 3.1.7 on 2021-03-31 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categories_Name', models.CharField(default='Category Name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='InventoryManagement Name', max_length=200)),
                ('brand', models.CharField(default='Brand Name', max_length=200)),
                ('price', models.IntegerField(blank=True)),
                ('weight', models.CharField(default='N\\A', max_length=200)),
                ('categories', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryManagement.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier_Name', models.CharField(default='Supplier Name', max_length=200)),
                ('Phone_num', models.IntegerField(blank=True)),
                ('Email', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(blank=True)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryManagement.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryManagement.supplier'),
        ),
    ]
