# Generated by Django 3.1.7 on 2021-10-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0002_auto_20210404_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sell',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
