# Generated by Django 3.1.7 on 2021-03-31 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InventoryManagement', '0001_initial'),
        ('CustomerManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_date', models.DateField(auto_now_add=True)),
                ('Price', models.IntegerField(blank=True, default=1)),
                ('quantity', models.IntegerField(blank=True)),
                ('Order_status', models.CharField(default='Order Status', max_length=200)),
                ('Order_date', models.DateField(auto_now_add=True)),
                ('customers', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CustomerManagement.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryManagement.product')),
            ],
        ),
    ]
