# Generated by Django 3.1.7 on 2021-04-04 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StaffManagement', '0002_auto_20210401_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Last_Name',
        ),
        migrations.AddField(
            model_name='staff',
            name='Full_name',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Designation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Expertise',
            field=models.TextField(max_length=200),
        ),
    ]
